TrajectoryPlannerROS:
  max_vel_x: 0.45 #0.45
  min_vel_x: 0.1 #0.1
  max_vel_theta: 0.3 #10.5
  min_vel_theta: -0.3 #-10.5
  min_in_place_vel_theta: 0.0

  acc_lim_theta: 10.2 #10.2
  acc_lim_x: 2.5
  acc_lim_y: 0.0
  
  max_rot_vel: 1.0
  min_rot_vel: 0.2

  vtheta_samples: 40

  escape_reset_dist: 0.25

  holonomic_robot: false
  
  escape_vel: -0.1

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 1.5
  xy_goal_tolerance: 2.0
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 2.0
  sim_granularity: 0.02
  angular_sim_granularity: 0.02
  vx_samples: 6
  vtheta_samples: 20
  controller_frequency: 20.0
