#This file contains common configuration options for the two costmaps used in the navigation stack 
#for more details on the parameters in this file, and a full list of the parameters used by the costmaps, 
#please see http://www.ros.org/wiki/costmap_2d.

plugins:
  #- {name: static_layer,      type: "costmap_2d::StaticLayer"}
  #- {name: obstacle_layer,    type: "costmap_2d::ObstacleLayer"}
  #- {name: sonar_layer,       type: "range_sensor_layer::RangeSensorLayer"}
  #- {name: voxel_layer,       type: "costmap_2d::VoxelLayer"}
  #- {name: inflation_layer,   type: "costmap_2d::InflationLayer"}


#The footprint of the robot and associated padding
footprint: [[-0.5, -0.25], [-0.5, 0.25], [0.2, 0.25], [0.2, -0.25]]
footprint_padding: 0.0

obstacle_layer:
  map_type: costmap

  #Voxel grid specific parameters
  origin_z: 0.0
  z_resolution: 0.1
  z_voxels: 10
  unknown_threshold: 9


  #Set the tolerance we're willing to have for tf transforms
  transform_tolerance: 0.6

  #Obstacle marking parameters
  obstacle_range: 2.0
  max_obstacle_height: 2.0
  raytrace_range: 1.9

  #Cost function parameters
  inflation_radius: 0.7
  cost_scaling_factor: 8.0

  #The cost at which a cell is considered an obstacle when a map is read from the map_server
  lethal_cost_threshold: 250

  #Configuration for the sensors that the costmap will use to update a map
  observation_sources: laser_scan_sensor point_cloud_sensor

  #Lidar params
  laser_scan_sensor: {sensor_frame: base_laser, data_type: LaserScan, topic: /scan, expected_update_rate: 0.5,
     marking: true, clearing: true, max_obstacle_height: 1, min_obstacle_height: 0.08}

  #Stereo camera params
  point_cloud_sensor: {sensor_frame: zed_center, data_type: PointCloud2, topic: /cloud_filtered, expected_update_rate: 1.0,
     marking: true, clearing: true, max_obstacle_height: 1.0, min_obstacle_height: 0.1, observation_persistence: 0.0, mark_threshold: 9}

#Ultrasonic sensors params
sonar_layer:
  topics: ['/ultrasonic_br', '/ultrasonic_bl'] #, '/ultrasonic_fl', '/ultrasonic_fr', '/ultrasonic_fmr', '/ultrasonic_fml']
  no_readings_timeout: 0.5
  clear_on_max_reading: false
  clear_threshold: 0.6
  mark_threshold: 0.95

  
